"""Init

Revision ID: 8fa0556121c8
Revises: b7086653bca2
Create Date: 2024-03-17 13:14:37.867662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fa0556121c8'
down_revision: Union[str, None] = 'b7086653bca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('score', sa.Float(), nullable=True))
    op.drop_column('grades', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('value', sa.INTEGER(), nullable=True))
    op.drop_column('grades', 'score')
    # ### end Alembic commands ###
