"""Init

Revision ID: f354b90070f5
Revises: 8fa0556121c8
Create Date: 2024-03-17 14:11:52.166368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f354b90070f5'
down_revision: Union[str, None] = '8fa0556121c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('value', sa.Integer(), nullable=True))
    op.add_column('grades', sa.Column('date', sa.Date(), nullable=True))
    op.drop_column('grades', 'date_received')
    op.drop_column('grades', 'score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('score', sa.FLOAT(), nullable=True))
    op.add_column('grades', sa.Column('date_received', sa.DATETIME(), nullable=True))
    op.drop_column('grades', 'date')
    op.drop_column('grades', 'value')
    # ### end Alembic commands ###
